[package]
name = "echor"
version = "0.1.0"
authors = ["Jamie Barnett <jamie.barnett@entura.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

clap = "2.33.0"
iron = "0.6.1"
router = "*"